### PR TITLE
Added the AWS signature test suite, which is presently failing

### PR DESCRIPTION
**Pull request by lox**
What started as me trying to use this library to do some S3 benchmarking turned into an epic debugging session. I'm getting incorrect signatures generated for S3 and the other services I tested. 

I decided to add the signature test suite from AWS in to see if they matched up, they do not. The first issue that jumps out is the incorrectly formatted Date header that gets added. The signature spec is confusing on the formatting of that header, but the http spec isn't. It should be a `http.TimeFormat` not a `iSO8601BasicFormat` I believe.

I'd love to know how this worked in the first place? @bmizerany I presume you've been using this without issue?

I'm running `go version go1.3 darwin/amd64`.

### CODE REVIEW

**Comment by lox** [comment]
With the date formatted correctly I get mostly passes. There is a failure on requests with duplicate headers, I presume due to the ordering. 

http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
`Append a comma-separated list of values for that header. If there are duplicate headers, the values are comma-separated. Do not sort the values in headers that have multiple values.`

**Comment by lox** [comment]
Blargh, although I'm still getting failures against S3, and Autoscale. Attached test cases.

**Comment by lox** [comment]
@sunjaec were you able to get aws4 working?

**Comment by sunjaec** [comment]
I was only able to get it to work with PostForm.

Working code fragment:

```
signingClient := &aws4.Client{
    Keys: &aws4.Keys{ accessKey, secretKey},
    Service: &aws4.Service{ some_service, "us-east-1" },
}

    formValues := make(url.Values)
    formValues.Add( requestParamKey, requestParamValue )

    ...

   if resp, err := signingClient.PostForm( .... 
```

**Comment by bmizerany** [comment]
The time format should be correct. The test suite AWS provided while I was working with this led me down all of the wrong paths becuase it was incorrectly formated and therofore of little to no help.

This library has worked for me in the past on many projects.

I only used PostForm, IIRC.

**Comment by bmizerany** [comment]
That isn't true. I used JSON for dynamo:

https://github.com/bmizerany/aws4/blob/master/dydb/dydb.go#L109

**Comment by lox** [comment]
@bmizerany yeah, very odd, reading this it does sound like they want a non-standard date header if there isn't an `x-amz-date` header: 

http://docs.aws.amazon.com/general/latest/gr/sigv4-date-handling.html

I'll ping my contact at AWS and find someone to ask about the test suite. It's pretty poor form if it's actually incorrect. I found a few bugs along the lines of windows line endings in the string to sign files, but aside from that it's working pretty well. 

FWIW, the bug it exposes in how you sign duplicate headers seems legit.

**Comment by radar** [comment]
This is great. I've been trying to use this library to make SNS requests and I've been running into signature issues as well. I'm very glad that someone else is debugging the signing process.

**Comment by lox** [comment]
I've put my notes together on issues I discovered with the signature test suite, sending them to amazon: 

https://gist.github.com/lox/9e00ce5428c8fe654011

**Comment by bmizerany** [comment]
Yup. Those are the issues I ran into. I had written tests to start but
finally flipped my desk when I found out they didn't match up with
production, and deleted my tests.

**Comment by lox** [comment]
Yeah, understandable :) I considered doing the same, but decided seeing as you wrote the awesome library the least I could do was try and get the test suite working against it.

**Comment by bmizerany** [comment]
Thank you. I am certainly very happy and appreciative of the help.

**Comment by lox** [comment]
BTW, apparently AWS agree the test suite is broken and have a developer working on it.

**Pull request closed without merging**
